ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- Master data
INSERT INTO MST_ENERGY_TYPE VALUES (1,'電気','ELECT',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_ENERGY_TYPE VALUES (2,'ガス','GAS',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_ENERGY_TYPE VALUES (3,'太陽光','SUNLIGHT',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_ENERGY_TYPE VALUES (4,'EV充電','EV',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);

INSERT INTO MST_INVOICE_STATUS VALUES (1,'001','DRAFT','未確定',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_INVOICE_STATUS VALUES (2,'002','ISSUED','発行済',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_INVOICE_STATUS VALUES (3,'003','PAID','入金済',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_INVOICE_STATUS VALUES (4,'004','CANCELLED','取消',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);

INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (1,1,1,'個人→個人',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (2,2,2,'法人→法人',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
INSERT INTO MST_CUSTOMER_TYPE_CONVERSION VALUES (3,3,3,'その他→その他',0,'SYSTEM',SYSTIMESTAMP,'SYSTEM',SYSTIMESTAMP);
COMMIT;

EXIT;
